from .settings_base import *
import os

DEBUG = False
ALLOWED_HOSTS = ["aquento.com", "www.aquento.com"]
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True
