# Generated by Django 6.0.3 on 2026-03-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Short summary for list views.', max_length=255)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, help_text='Custom meta title for this news page.', max_length=255)),
                ('seo_description', models.CharField(blank=True, help_text='Custom meta description for this news page.', max_length=255)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home', 'Homepage extra content'), ('production', 'Production'), ('contacts', 'Contacts'), ('instructions', 'Instructions landing'), ('custom', 'Custom page')], default='custom', help_text='Logical key to refer to this page in views/templates.', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL slug for this page.', max_length=200, unique=True)),
                ('content', models.TextField(blank=True, help_text='Main page content (HTML or plain text).')),
                ('image', models.ImageField(blank=True, help_text='Optional header/hero image for the page.', null=True, upload_to='pages/')),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, help_text='Custom meta title for this page.', max_length=255)),
                ('seo_description', models.CharField(blank=True, help_text='Custom meta description for this page.', max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name, e.g. Aquento ULTRA01', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug, e.g. aquento-ultra01', max_length=200, unique=True)),
                ('model_code', models.CharField(blank=True, help_text='Internal model code, e.g. AQ-ULTRA01', max_length=100)),
                ('compatible_models', models.TextField(blank=True, help_text='Comma-separated list of OEM compatible models (ULTRAWF, EPTWFU01, ...).')),
                ('short_description', models.CharField(blank=True, help_text='Short tagline shown in lists.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Full description for the product detail page.')),
                ('image', models.ImageField(blank=True, help_text='Main product image.', null=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage as a featured product.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this product from the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, help_text='Custom meta title for this product page.', max_length=255)),
                ('seo_description', models.CharField(blank=True, help_text='Custom meta description for this product page.', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True, help_text='Instruction text (HTML or plain text).')),
                ('pdf_file', models.FileField(blank=True, help_text='Optional PDF file with instructions.', null=True, upload_to='instructions/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo_title', models.CharField(blank=True, help_text='Custom meta title for this instruction page.', max_length=255)),
                ('seo_description', models.CharField(blank=True, help_text='Custom meta description for this instruction page.', max_length=255)),
                ('product', models.ForeignKey(help_text='Product this instruction belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.product')),
            ],
            options={
                'ordering': ['product', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Background image for the slide.', null=True, upload_to='slides/')),
                ('button_text', models.CharField(blank=True, help_text='Text for the call‑to‑action button.', max_length=100)),
                ('button_url', models.URLField(blank=True, help_text='Absolute or relative URL for the button.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of slides on the homepage (lower appears first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(blank=True, help_text='Optional news item to link to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='core.news')),
                ('product', models.ForeignKey(blank=True, help_text='Optional product to link to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='core.product')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
