# Generated by Django 6.0.3 on 2026-03-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supportthread_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportthread',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
