# Generated by Django 6.0.3 on 2026-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_supportthread_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_url',
            field=models.URLField(blank=True, help_text='Full URL to this product on Amazon.', verbose_name='Amazon product URL'),
        ),
    ]
