# Generated by Django 6.0.3 on 2026-03-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_amazon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Optional badge text, e.g. NEW / AQ-ULTRA01', max_length=50),
        ),
    ]
