# Generated by Django 6.0.3 on 2026-03-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_slide_badge_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='bullet_1',
            field=models.CharField(blank=True, help_text='First bullet point', max_length=120),
        ),
        migrations.AddField(
            model_name='slide',
            name='bullet_2',
            field=models.CharField(blank=True, help_text='Second bullet point', max_length=120),
        ),
        migrations.AddField(
            model_name='slide',
            name='bullet_3',
            field=models.CharField(blank=True, help_text='Third bullet point', max_length=120),
        ),
    ]
